const cartActionTypes = {
    TOGGLE_CART_DROPDOWN_STATUS: 'TOGGLE_CART_DROPDOWN_STATUS',
    ADD_ITEM: 'ADD_TIME',
    REMOVE_ITEM: 'REMOVE_ITEM',
    REMOVE_ITEM_COLLECTION: 'REMOVE_ITEM_COLLECTION'
}

export default cartActionTypes;